export const ADD_TABLE = "ADD_TABLE";

export const ADD_VEG_STARTERS = "ADD_VEG_STARTERS";
export const ADD_VEG_MAINCOURSE = "ADD_VEG_MAINCOURSE";

export const ADD_NONVEG_STARTERS = "ADD_NONVEG_STARTERS";
export const ADD_NONVEG_MAINCOURSE = "ADD_NONVEG_MAINCOURSE";

export const REMOVE_VEG_STARTERS = "REMOVE_VEG_STARTERS";
export const REMOVE_VEG_MAINCOURSE = "REMOVE_VEG_MAINCOURSE";

export const REMOVE_NONVEG_STARTERS = "REMOVE_NONVEG_STARTERS";
export const REMOVE_NONVEG_MAINCOURSE = "REMOVE_NONVEG_MAINCOURSE";

export const ADD_TO_CART = "ADD_TO_CART ";

export const DELETE_ITEMS = "DELETE_ITEMS";

export const INCREMENT_ITEM = "INCREMENT_ITEM";

export const DECREMENT_ITEM = "DECREMENT_ITEM";
